export const MESSAGE_PILOT_VERSION = "hanyao-line-message-pilot-v1";

export const MESSAGE_PILOT = {
  status: "CANDIDATE_ONLY",
  pilotCampaign: "冷氣維修",
  customerId: "4801404246",
  landingPath: "/services/ac-repair/",
  provider: {
    uiPlatform: "LINE",
    lineId: "@451vpomq",
    verificationLink: "https://line.me/R/ti/p/@451vpomq",
    evidenceClass: "ACCOUNT_UI_SNAPSHOT_REQUIRES_FRESH_RECHECK",
    apiV25LineProviderSupported: false,
    mutationRoute: "GOOGLE_ADS_UI_ONLY_AFTER_HUMAN_GATE",
  },
  starterMessageCandidates: [
    "您好，我的冷氣有問題，想先傳照片或症狀請協助判斷。",
    "您好，我想詢問冷氣維修，稍後會傳照片與所在地區，請協助評估。",
  ],
  canonicalConversion: {
    name: "HY - Verified LINE Contact",
    conversionActionId: "7674301565",
    mustRemainPrimary: false,
    messageAssetEventsMayWriteCanonicalConversion: false,
  },
  googleMessageGoal: {
    expectedAccountGoalLabel: "Leads from Messages",
    expectedCampaignChoiceLabel: "Messages from your ads",
    mayReplaceCanonicalIdentity: false,
    mayBecomePrimaryWithoutSeparateHumanApproval: false,
    mayChangeCampaignOptimizationSetWithoutSeparateHumanApproval: false,
  },
  biddingSafeguard: {
    expectedCurrentFamilyFromPlanSnapshot: "TARGET_SPEND / MAXIMIZE_CLICKS_FAMILY",
    allowedToChangeBiddingInPilotSetup: false,
    stopIfUiRequiresConversionBasedBidding: true,
    fallback: "ISOLATED_CAMPAIGN_OR_EXPERIMENT_REQUIRES_SEPARATE_BUDGET_AND_STRATEGY_APPROVAL",
  },
  servingCaveats: {
    android: "GLOBALLY_ELIGIBLE",
    iosTaiwan: "NOT_IN_CURRENT_ELIGIBLE_COUNTRY_LIST",
    otherAssetsCanServeWithMessageButtonAtSameTime: false,
  },
  measurement: {
    canonicalKpi: "TOTAL_REAL_CONTACTS",
    messageClicksAreVerifiedContacts: false,
    requiredBreakouts: [
      "eligible message impressions",
      "message clicks",
      "message conversations when available",
      "Android message performance",
      "iOS visibility or absence",
      "call clicks / tracked calls",
      "irrelevant chats",
      "cost per real conversation",
    ],
    planObservationFloorDays: 14,
    planPreferredMessageClicks: 100,
    sampleRuleSource: "HANYAO_PLAN_HEURISTIC_NOT_GOOGLE_PLATFORM_RULE",
  },
  providerPrestateRequired: [
    "advertiser verification status",
    "message asset beta eligibility still present",
    "fresh LINE platform + Line ID fields in UI",
    "current campaign bidding strategy",
    "current campaign conversion goals and optimization set",
    "current call / lead-form asset associations",
    "existing message asset inventory",
    "current policy / verification status",
  ],
  dispatchGate: "HG-ADS-MESSAGE-PILOT",
  googleAdsMutationApplied: false,
  prohibitedMutations: [
    "budget",
    "bidding strategy",
    "HY - Verified LINE Contact identity",
    "HY - Verified LINE Contact Primary status",
    "broad match expansion",
    "AI Max",
    "fake HY token",
    "message click -> HY verified conversion",
  ],
} as const;
